export const SET_POSTS = 'SET_POSTS'
export const SET_NEW_POST = 'SET_NEW_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'
export const SET_COMMENTS = 'SET_COMMENTS'
export const SET_NEW_COMMENT = 'SET_NEW_COMMENT'
