export const SIGN_IN_SET_USERS = 'SIGN_IN_GET_USERS'
export const SIGN_IN_LOG_IN = 'SIGN_IN_LOG_IN'
export const SIGN_IN_LOG_OUT = 'SIGN_IN_LOG_OUT'
export const USER_CHECK_LOGIN_STATUS = 'USER_CHECK_LOGIN_STATUS'
